schema_version: 1

context:
  version: "1.0.9"

package:
  name: spyder-themes
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spyder-themes/spyder_themes-${{ version }}.tar.gz
  sha256: b45a2f381823dd812af51cb81b3710d412b440919d9ea98fe4b984fead2bb7f8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - spyder_themes
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Collection of themes for Spyder IDE
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/spyder-themes/

extra:
  recipe-maintainers:
    - conradolandia
    - ccordoba12
    - dalthviz
